export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const REMOVE_RESOURCE_MEMBER = "REMOVE_RESOURCE_MEMBER";
export const ADD_RESOURCE_MEMBER = "ADD_RESOURCE_MEMBER";

export const UPDATE_RESOURCES = "UPDATE_RESOURCES";
export const ADD_RESOURCE = "ADD_RESOURCE";
export const CHANGE_SELECTED_COMPUTER = "CHANGE_SELECTED_COMPUTER";
